package:
  name: pyroms
  version: "0.1.1"

source:
#  git_rev: 
#  git_url: https://github.com/bilgetutak/pyroms.git
   path: /opt/depo/model/git_contrib/pyroms/pyroms

build:
  preserve_egg_dir: True
  rpaths:
    - lib/python2.7/site-packages/pyroms/lib

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - basemap
    - netcdf4
    - pyroms_toolbox
    - bathy_smoother
    - ipython

# test:
#   imports:
#     - pyroms

about:
  home: https://github.com/bilgetutak/pyroms.git
  license: BSD
  license_file: LICENSE.txt